import os
import platform

env = Environment()
opt = env.Clone(CC='clang', CXX='clang++', CCFLAGS=['-g', '-O3', '-Wall'], CXXFLAGS="-std=c++11")

boost_libs = ['boost_regex', 'boost_system']

if os.name == "posix" and platform.system() == "Darwin":
    for index, lib in enumerate(boost_libs):
        concat_lib = lib + "-mt"
        boost_libs[index] = concat_lib

libs = ['curl', 'libcppnetlib-uri']
libs.append(boost_libs)

# Build the program
pGet = opt.Program(target = "pGet_bin", source = [Glob('**/*.cpp'), 'pGet.cpp'], LIBS = libs, CPPPATH = ['../lib/cpp-netlib'], LIBPATH = ['../lib/cpp-netlib/libs/network/src'])

# Install the binary into a folder
opt.Install('../bin', pGet)
