env = Environment()
opt = env.Clone(CCFLAGS=['-pthread', '-O3', '-Wall'])
curlP = opt.Program (target = "curlP", source = ['curlP.cpp', 'curl/curl_file.cpp'], LIBS = ['curl', 'PocoNet', 'PocoFoundation'])
opt.Install('../bin', curlP)
